# Generated by Django 3.2.8 on 2022-04-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0006_product_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='page',
        ),
    ]
