# Generated by Django 3.2.8 on 2022-04-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0015_auto_20220419_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_details',
            field=models.TextField(null=True),
        ),
    ]
