# Generated by Django 4.0.4 on 2022-04-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0016_alter_tasks_task_details'),
        ('accord', '0016_auto_20220426_2203'),
    ]

    operations = [
    ]
