# Generated by Django 3.2.8 on 2022-05-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0017_auto_20220502_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='PENDING', max_length=20, null=True),
        ),
    ]
