# Generated by Django 3.2.8 on 2022-05-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0019_auto_20220502_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
