# Generated by Django 4.0.4 on 2022-06-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0018_order_bkash_number_order_bkash_txn_id_and_more'),
        ('accord', '0023_order_product'),
    ]

    operations = [
    ]
