# Generated by Django 4.0.4 on 2022-06-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0024_merge_20220602_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
