# Generated by Django 3.2.8 on 2022-06-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0024_auto_20220621_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_to_number',
            field=models.CharField(choices=[(None, 'Select Bkash/Nagad number you paid to'), ('01797407811', '01797407811'), ('01960008530', '01960008530'), ('01309956343', '01309956343'), ('01609212434', '01609212434'), ('01941171107', '01941171107')], default=None, max_length=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='bkash_txn_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
