# Generated by Django 3.2.8 on 2022-06-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0026_alter_order_paid_to_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='money_received_by',
        ),
    ]
