# Generated by Django 3.2.8 on 2022-07-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0028_auto_20220701_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
