# Generated by Django 3.2.8 on 2022-07-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0029_alter_product_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avatar',
            field=models.ImageField(default='jersey-avatar.png', null=True, upload_to=''),
        ),
    ]
