# Generated by Django 3.2.8 on 2022-07-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0030_alter_product_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='sleeve',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
