# Generated by Django 4.0.4 on 2022-07-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0025_alter_order_quantity'),
        ('accord', '0031_order_product_sleeve'),
    ]

    operations = [
    ]
