# Generated by Django 3.2.8 on 2022-07-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0031_order_product_sleeve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='full_sleeve_price',
        ),
        migrations.AddField(
            model_name='product',
            name='half_sleeve_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='sleeve',
            field=models.CharField(blank=True, default='half', max_length=200, null=True),
        ),
    ]
