# Generated by Django 3.2.8 on 2021-10-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0002_auto_20211014_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
