# Generated by Django 3.2.8 on 2022-04-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0008_auto_20220418_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
