# Generated by Django 3.2.8 on 2022-04-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accord', '0009_auto_20220418_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
